---
title: "Cesta básica dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

# Petrolina 



```{r, echo = FALSE}

produtos <- c("Carne (kg)", "Leite Integral (Litro)", "Feijão Carioca (Kg)", "Arroz (Kg)", "Farinha (Kg)", 
              "Tomate (kg)", "Pão Frances (kg)", "Café em Pó (Kg)", "Banana (Dúzia)", "Açúcar (Kg)", 
              "Óleo Soja (900 ml)", "Margarina (250g)", "Custo Total da Cesta Básica")

qtd <- c(4.5, 6, 4.5, 3.6, 3, 12, 6, 0.3, 7.5, 3, 0.833, 3, NA)

custo_juazeiro <- c(160.69, 34.21, 36.25, 22.88, 19.53, 92.29, 76.89, 9.61, 94.62, 12.84, 5.56, 11.60, 576.98)

variacao_mes_juazeiro <- c(-0.66, -0.22, -3.87, 0.70, -0.34, 29.63, 0.40, 4.86, 4.68, 4.86, 0.15, -4.00, 4.28)


acumulad0_12_meses_juazeiro <- c(-4.72,-5.40,-12.03,25.58,-0.88,40.19,0.76,2.53,44.65,11.75,-26.03,-13.82,6.71)


custo_petrolina <- c(156.77, 34.32, 40.88, 24.55, 18.67, 110.74, 81.63, 10.30, 111.06, 14.12, 6.29, 10.95, 620.29)

variacao_mes_petrolina <- c(-0.66, -2.04,1.15,-2.12,-0.62,43.63,-1.85,2.27,5.09,6.44,2.75,-1.97,6.26)

acumulad0_12_meses_petrolina <- c(-3.69, -5.42, -4.41, 27.7, -1.4, 71.01, -1.96, 0.9, 63.12, 17.78, -17.98, -9.25,14.78)





data_frame <- data.frame(Produtos = produtos, 
                         Qtd = qtd, 
                         `custo_juazeiro` = custo_juazeiro, 
                         `variacao_mes_juazeiro` = variacao_mes_juazeiro, 
                         `acumulad0_12_meses_juazeiro` = acumulad0_12_meses_juazeiro,
                         `custo_petrolina` = custo_petrolina,
                         `variacao_mes_petrolina` = variacao_mes_petrolina,
                         `acumulad0_12_meses_petrolina` = acumulad0_12_meses_petrolina)

```

```{r, echo=FALSE}

produtos2 <- c("Carne (kg)", "Leite Integral (Litro)", "Feijão Carioca (Kg)", "Arroz (Kg)", "Farinha (Kg)", 
              "Tomate", "Pão Frances", "Café em Pó (Kg)", "Banana (Dúzia/Kg)", "Açúcar (Kg)", 
              "Óleo de Soja (900 ml)", "Margarina (250g)")



maximo <- c(42.99, 8.99, 11.15, 10.35, 8.99, 10.90, 14.50, 10.99, 17.79, 5.50, 11.99, 6.25)
minimo <- c(26.95, 4.09, 5.39, 5.19, 4.29, 3.99, 10.90, 5.39, 7.18, 3.39, 5.45, 0.99)
diferenca_maximo <- c(59.52, 119.80, 106.86, 99.42, 109.56, 173.18, 33.03, 103.90, 147.77, 62.24, 120.00, 531.31)
maximo_2 <- c(45.50, 10.99, 11.99, 11.99, 12.90, 12.99, 15.00, 13.90, 19.17, 6.89, 13.75, 4.99)
minimo_2 <- c(25.99, 3.99, 6.99, 4.75, 3.89, 5.29, 11.90, 5.99, 5.88, 3.49, 5.48, 1.49)
diferenca_maximo_2 <- c(75.07, 175.44, 71.53, 152.42, 231.62, 145.56, 26.05, 132.05, 226.05, 97.42, 150.91, 234.90)

# Criando o DataFrame
data_frame2 <- data.frame(Produtos = produtos2,
                         `Máximo_juazeiro` = maximo,
                         `Mínimo_juazeiro` = minimo,
                         `Diferença_porcentagem_juazeiro` = diferenca_maximo,
                         `Máximo_petrolina` = maximo_2,
                         `Mínimo_petrolina` = minimo_2,
                         `Diferença_petrolina` = diferenca_maximo_2)


```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
library(ggplot2)
library(plotly)

data_frame$Produtos<- reorder(data_frame$Produtos, data_frame$custo_petrolina)

GP <- ggplot(data_frame, aes(x = Produtos, y = custo_petrolina )) +
  geom_bar(stat = "identity", position = "dodge", col = "skyblue", fill = "skyblue") +
  labs(title = "Custo dos produtos em Petrolina",
       x = "Produtos",
       y = "Custo (R$)",
       fill = "Local") +
  theme_minimal() + 
   scale_y_continuous(n.breaks = 20)+
   scale_x_discrete(expand = expansion(add = c(0.1, 0.1)))+
  coord_flip()

ggplotly(GP)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
 ggplot(data_frame, aes(x = "", y = custo_petrolina, fill = Produtos)) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar(theta = "y") +
  labs(title = "Custo dos Produtos em Petrolina",
       x = NULL,  # Remove o rótulo do eixo x
       y = NULL,  # Remove o rótulo do eixo y
       fill = "Produtos") +
  theme_minimal() +
  theme(axis.text.x = element_blank(),  # Remove os textos dos eixos
        axis.ticks = element_blank(),   # Remove os ticks dos eixos
        panel.grid = element_blank())



```

### Chart C

```{r}
library(knitr)
kable(data_frame)
```

# Juazeiro


Column {data-width=650}
-----------------------------------------------------------------------

### Chart D

```{r}
library(ggplot2)


data_frame$Produtos<- reorder(data_frame$Produtos, data_frame$custo_juazeiro)

GJ <- ggplot(data_frame, aes(x = Produtos, y = custo_juazeiro )) +
   geom_bar(stat = "identity", position = "dodge", col = "#F8E289", fill = "#F8E289") +
   labs(title = "Custo dos produtos em Juazeiro",
        x = "Produtos",
        y = "Custo (R$)",
        fill = "Local") +
   theme_minimal() + 
   scale_y_continuous(n.breaks = 20)+
   scale_x_discrete(expand = expansion(add = c(0.5, 0.5)))+
  coord_flip()

ggplotly(GJ)
 
```


Column {data-width=350}
-----------------------------------------------------------------------

### Chart E

```{r}
ggplot(data_frame, aes(x = "", y = custo_juazeiro, fill = Produtos)) +
  geom_bar(width = 1, stat = "identity", color = "white") +
  coord_polar(theta = "y") +
  labs(title = "Custo dos Produtos em Juazeiro",
       x = NULL,  # Remove o rótulo do eixo x
       y = NULL,  # Remove o rótulo do eixo y
       fill = "Produtos") +
  theme_minimal() +
  theme(axis.text.x = element_blank(),  # Remove os textos dos eixos
        axis.ticks = element_blank(),   # Remove os ticks dos eixos
        panel.grid = element_blank(),   # Remove as linhas de grade
        panel.border = element_blank())
```

### Chart F

```{r}
kable(data_frame2)
```


